name=BlockMalloc
version=1.0.0
author=Anatoli Arkhipenko <arkhipenko@hotmail.com>
maintainer=Anatoli Arkhipenko <arkhipenko@hotmail.com>
sentence=MCU-friendly memory allocation module
paragraph=Memory allocation in blocks of bytes to prevent fragmentation
category=Memory
url=https://github.com/arkhipenko/BlockMalloc
architectures=*
